### ISSUE TITLE
nil input causes predicate errors

### ISSUE THREAD

**Issue by fran-worley** [dry-rb/dry-validation#150]
I apologise if this has been covered elsewhere but:
In adding additional specs following the PR by @jodosha I've found the following errors coming through from dry-logic:

```
  1) Predicates: Excludes with required with nil input is successful
     Failure/Error: hash[name] = rule.(input)
     
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicates.rb:155:in `block in <module:Predicates>'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicate.rb:22:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicate.rb:22:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/value.rb:13:in `apply'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/value.rb:9:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/composite.rb:42:in `call'
     # ./lib/dry/validation/schema.rb:229:in `block in rule_results'
     # ./lib/dry/validation/schema.rb:228:in `each'
     # ./lib/dry/validation/schema.rb:228:in `each_with_object'
     # ./lib/dry/validation/schema.rb:228:in `rule_results'
     # ./lib/dry/validation/schema.rb:212:in `apply'
     # ./lib/dry/validation/schema.rb:188:in `call'
     # ./spec/support/predicates_integration.rb:5:in `result'
     # ./spec/integration/form/predicates/excludes_spec.rb:29:in `block (4 levels) in <top (required)>'

  2) Predicates: Excludes as macro with required with value with nil input is successful
     Failure/Error: hash[name] = rule.(input)
     
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicates.rb:155:in `block in <module:Predicates>'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicate.rb:22:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicate.rb:22:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/value.rb:13:in `apply'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/value.rb:9:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/composite.rb:42:in `call'
     # ./lib/dry/validation/schema.rb:229:in `block in rule_results'
     # ./lib/dry/validation/schema.rb:228:in `each'
     # ./lib/dry/validation/schema.rb:228:in `each_with_object'
     # ./lib/dry/validation/schema.rb:228:in `rule_results'
     # ./lib/dry/validation/schema.rb:212:in `apply'
     # ./lib/dry/validation/schema.rb:188:in `call'
     # ./spec/support/predicates_integration.rb:5:in `result'
     # ./spec/integration/form/predicates/excludes_spec.rb:143:in `block (6 levels) in <top (required)>'

  3) Predicates: Excludes as macro with optional with value with nil input is successful
     Failure/Error: hash[name] = rule.(input)
     
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicates.rb:155:in `block in <module:Predicates>'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicate.rb:22:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicate.rb:22:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/value.rb:13:in `apply'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/value.rb:9:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/composite.rb:26:in `call'
     # ./lib/dry/validation/schema.rb:229:in `block in rule_results'
     # ./lib/dry/validation/schema.rb:228:in `each'
     # ./lib/dry/validation/schema.rb:228:in `each_with_object'
     # ./lib/dry/validation/schema.rb:228:in `rule_results'
     # ./lib/dry/validation/schema.rb:212:in `apply'
     # ./lib/dry/validation/schema.rb:188:in `call'
     # ./spec/support/predicates_integration.rb:5:in `result'
     # ./spec/integration/form/predicates/excludes_spec.rb:313:in `block (6 levels) in <top (required)>'

  4) Predicates: Excludes with optional with nil input is successful
     Failure/Error: hash[name] = rule.(input)
     
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicates.rb:155:in `block in <module:Predicates>'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicate.rb:22:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/predicate.rb:22:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/value.rb:13:in `apply'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/value.rb:9:in `call'
     # /Users/francesworley/.rvm/gems/ruby-2.2.4/bundler/gems/dry-logic-e649fad58546/lib/dry/logic/rule/composite.rb:26:in `call'
     # ./lib/dry/validation/schema.rb:229:in `block in rule_results'
     # ./lib/dry/validation/schema.rb:228:in `each'
     # ./lib/dry/validation/schema.rb:228:in `each_with_object'
     # ./lib/dry/validation/schema.rb:228:in `rule_results'
     # ./lib/dry/validation/schema.rb:212:in `apply'
     # ./lib/dry/validation/schema.rb:188:in `call'
     # ./spec/support/predicates_integration.rb:5:in `result'
     # ./spec/integration/form/predicates/excludes_spec.rb:85:in `block (4 levels) in <top (required)>'
```
Happy to move this to dry-logic if necessary but is there a better way of handling predicates on nil in dry-validation?
