### ISSUE TITLE
Custom error namespace for custom schemas like JSON and Form

### ISSUE THREAD

**Issue by backus** [dry-rb/dry-validation#168]
It would be nice if `Dry::Validation.JSON` and `Dry::Validation.Form` had their own error message namespace. Something like this:

```yaml
en:
  schema:
    errors: &default
      array?: "must be an array"

      empty?: "must be empty"

      # ...

      hash?: "must be a hash"

      # ...

  json:
    errors:
      <<: *default

      hash?: "must be an object"
```

This way, when you build a validation using one of this domain specific schemas you would get domain specific messages:

```ruby
DEFINITION = proc { required('thing').value(:hash?, :empty?) }

json_schema   = Dry::Validation.JSON(&DEFINITION)
normal_schema = Dry::Validation.Schema(&DEFINITION)

input = { 'thing' => [] }

normal_schema.call(input).messages # => {"thing"=>["must be a hash", "must be empty"]}
json_schema.call(input).messages   # => {"thing"=>["must be an object", "must be empty"]}
```
