### ISSUE TITLE
Rule custom error message

### ISSUE THREAD

**Issue by stefkin** [dry-rb/dry-validation#372]
I have a rule that looks somewhat like:

```
  rule(any_value_filled: DECIMAL_FIELDS) do |*fields|
    fields.reduce(fields.first.filled?) { |acc, f| acc | f.filled? }
  end
```

it produces the error which looks like "must be filled or must be filled" repeated for each of the DECIMAL_FIELDS I have. Which looks silly when you have a lot of arguments in the rule.

I couldn't find a way to override message for the rule with multiple arguments.
When I provide a custom message for the rule it gets repeated the same way as "must be filled" does.

It would be nice to have a way of specifying multi-arg rule message in a way similar to the following: 
```
en:
  errors:
    size?:
      arg:
        default: "size must be %{num}"
        range: "size must be within %{left} - %{right}"
```
