### ISSUE TITLE
Detailed errors for API's

### ISSUE THREAD

**Issue by Mistgun** [dry-rb/dry-validation#432]
It would be pretty cool if we could define how errors should be build. I'm talking about something like that: https://stackoverflow.com/a/19673344/3837806

**Comment by cmcolinh** [comment]
This certainly seems like it should be possible.  If you extend or redefine Dry::Validation::Messages::YAML#flat_hash to make exceptions for when it flattens the hash (perhaps to make a limit to the depth of the recursion), it seems feasible that you could then writing something like this in config/errors.yml
```
en:
  errors:
    rules:
      msiisdn:
        key?:
          code: 101
          message: "can not be blank"
        filled?:
          code: 101
          message: "can not be blank"
        format?:
          code: 102
          message: "not compliant with msisdn format"
```
