### ISSUE TITLE
NoMethodError undefined method 'data' for [#<Dry::Schema::Messages::Template text="not right">, {}]:Array

### ISSUE THREAD

**Issue by olleolleolle** [dry-rb/dry-validation#503]
This Issue is about the build failure https://travis-ci.org/dry-rb/dry-validation/builds/514037046 

> NoMethodError:  undefined method `data' for [#<Dry::Schema::Messages::Template text="not right">, {}]:Array

<details>

```
Randomized with seed 45521
..................F.........FFFFFFFFFFFFFFF.F....F.FF.FFF.....
Failures:
  1) Dry::Validation::Evaluator setting key failures using via explicit path with a symbol sets error under specified key
     Failure/Error: text = template.(template.data(tokens))
     
     NoMethodError:
       undefined method `data' for [#<Dry::Schema::Messages::Template text="not right">, {}]:Array
     # ./lib/dry/validation/messages/resolver.rb:65:in `message'
     # ./lib/dry/validation/messages/resolver.rb:36:in `block in call'
     # ./lib/dry/validation/error.rb:26:in `evaluate'
     # ./lib/dry/validation/error_set.rb:86:in `block in freeze'
     # ./lib/dry/validation/error_set.rb:84:in `each'
     # ./lib/dry/validation/error_set.rb:84:in `freeze'
     # ./lib/dry/validation/result.rb:129:in `freeze'
     # ./lib/dry/validation/result.rb:24:in `new'
     # ./lib/dry/validation/contract.rb:90:in `call'
     # ./spec/integration/contract/evaluator/failure_spec.rb:64:in `block (4 levels) in <top (required)>'
     # ./Rakefile:13:in `block in <top (required)>'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/ruby/2.4.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
  2) Dry::Validation::Messag
```

</details>
