### ISSUE TITLE
Default error message for registered macro

### ISSUE THREAD

**Issue by Sphaerus** [dry-rb/dry-validation#646]
Provide a default error message for registered macros which would not consider attributes using the macro

## Examples

```
register_macro(:validity) do
    key.failure(:macro_invalid)
```

when using this macro for, lets say, `email` attribute, dry will look for error message in errors.yml like this:

```
en:
  dry_validation:
    errors:
      rules:
        email:
          macro_invalid:  error message
```

instead id like to defined a default error message for every `macro_invalid` error there is:

```
en:
  dry_validation:
    errors:
      rules:
        default:
          macro_invalid:  error message
```
Is this already possible somehow, and if not would you consider such a feature to be reasonable?
