### ISSUE TITLE
Support per-key custom errors for array paths

### ISSUE THREAD

**Issue by adamransom** [dry-rb/dry-validation#663]
Given the following contract:

```ruby
config.messages.backend = :i18n
config.message.namespace = :my_contract

params do
  required(:people).filled(:array)
end

rule(:people).each do
   key.failure(:invalid) if person_invalid?
end
```

it should be possible to define the message for `:invalid` under `:people` as follows:

```yaml
en:
  dry_validation:
    errors:
      my_contract:
        rules:
          people:
            invalid: 'Something'
```

However, currently, this gives an error that the `:invalid` key can't be found under `people.0`. Instead, you need to define the translations as such:

```yaml
en:
  dry_validation:
    errors:
      my_contract:
        invalid: 'Something'
```

_Issue originally reported [on Discourse](https://discourse.dry-rb.org/t/i18n-paths-for-array-rules/1097)_

- Affects my production application: **NO**
- Ruby version: 2.6.5
