### ISSUE TITLE
Deep rules messages example?

### ISSUE THREAD

**Issue by badlamer** [dry-rb/dry-validation#82]
```yml
en:
  errors:
    rules:
      email:
        filled?: "the email is missing"

      user:
        filled?: "name cannot be blank"

        rules:
          address:
            filled?: "You gotta tell us where you live"
```

Please example for more nested rule message.
